### ISSUE TITLE
example Hello.py Don't Works

### ISSUE THREAD

**Issue by latot** [libfuse/python-fuse#27]
Hi, actually when we run the example, finish with the next error:
```
python3 hello.py
fuse: missing mountpoint parameter
Traceback (most recent call last):
  File "hello.py", line 91, in <module>
    main()
  File "hello.py", line 88, in main
    server.main()
  File "/usr/lib/python3/dist-packages/fuse.py", line 754, in main
    main(**d)
fuse.FuseError: filesystem initialization failed
```
Thx

**Comment by latot** [comment]
nothing, just i don't specify the path.

**Comment by nomadbyte** [comment]
In case anyone else stumbles on this. Just to demo the usage:

```
$ mkdir /tmp/testfuse
$ python3 hello.py /tmp/testfuse
$ ls /tmp/testfuse
hello
$ cat /tmp/testfuse/hello
Hello World!
```

So the FUSE fs was mounted on /tmp/testfuse. Listing the contents shows the `hello` file, which contains `Hello World!`
